name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [2.12.15]
        jvm: [adopt@1.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Mill
        uses: jodersky/setup-mill@master
        with:
          mill-version: 0.9.9
      - name: Install simulators
        run: sudo apt-get install -y verilator iverilog
      - name: Install other dependencies
        run: sudo apt-get install -y gcc libboost-dev
      - name: Compile
        run: mill fpu-wrappers.compile
      - name: Test
        run: mill fpu-wrappers.test